# Generated by Django 5.1.4 on 2025-01-04 17:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Stacker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
                ('distance', models.IntegerField(default=0)),
                ('emptyDistance', models.IntegerField(default=0)),
                ('time', models.IntegerField(default=0)),
                ('emptyTime', models.IntegerField(default=0)),
                ('material_load', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('storing', models.BooleanField()),
                ('stored_on', models.DateTimeField(null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(default='', max_length=200)),
                ('arrived_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('served_on', models.DateTimeField(null=True)),
                ('type', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('priority', models.IntegerField(null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_order', to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_control', models.BooleanField()),
                ('weight_control_value', models.IntegerField(default=0)),
                ('weight_control_from_story', models.IntegerField(default=0)),
                ('vertical_speed', models.IntegerField()),
                ('horizontal_speed', models.IntegerField()),
                ('material_durability', models.IntegerField()),
                ('stacker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stacker')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('product', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_storage', to='core.product')),
            ],
        ),
        migrations.AddField(
            model_name='stacker',
            name='storage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.storage'),
        ),
        migrations.AddField(
            model_name='product',
            name='storage',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_product', to='core.storage'),
        ),
        migrations.AddField(
            model_name='stacker',
            name='strategy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.strategy'),
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.ManyToManyField(related_name='strategies', to='core.strategy')),
            ],
        ),
        migrations.CreateModel(
            name='StrategySimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tours', models.IntegerField(default=-1)),
                ('empty_tours', models.IntegerField(default=-1)),
                ('distance', models.IntegerField(default=-1)),
                ('empty_distance', models.IntegerField(default=-1)),
                ('time', models.IntegerField(default=-1)),
                ('empty_time', models.IntegerField(default=-1)),
                ('tour_efficiency', models.FloatField(default=-1.0)),
                ('distance_efficiency', models.FloatField(default=-1.0)),
                ('time_efficiency', models.FloatField(default=-1.0)),
                ('maintenance', models.IntegerField(default=0)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.simulation')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.strategy')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('empty_time', models.IntegerField()),
                ('time', models.IntegerField()),
                ('empty_distance', models.IntegerField()),
                ('distance', models.IntegerField()),
                ('material_load', models.IntegerField(default=0)),
                ('type', models.CharField(max_length=200, null=True)),
                ('x1', models.IntegerField(default=0)),
                ('x2', models.IntegerField(default=0)),
                ('y1', models.IntegerField(default=0)),
                ('y2', models.IntegerField(default=0)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tours', to='core.product')),
                ('stacker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stacker')),
            ],
        ),
    ]
